### ISSUE TITLE
Plan: add `ctx` to event structure for metadata such as otel IDs

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest#107]

**Comment by ayewo** [comment]
Hi @tonyhb!

Can you share more details regarding this issue? To get started, could you kindly point me to where should I be looking?

**Comment by tonyhb** [comment]
Hey @ayewo!  We're planning this out and would like to add this within the next ~month.  The idea being, we'll automatically apply trace IDs and carry over baggage within `ctx` in events.  This _currently_ doesn't exist.

**Comment by rukundob451** [comment]
@tonyhb is this still available?
