### ISSUE TITLE
Scheduled event throws:`error creating run state: context canceled`

### ISSUE THREAD

**Issue by homanp** [inngest/inngest#1260]
**Describe the bug**
I'm seeing the following error when running scheduled function locally.

**Screenshots / Stack trace dump**
<img width="1014" alt="Screenshot 2024-04-04 at 18 25 05" src="https://github.com/inngest/inngest/assets/2464556/d53dd06e-2521-4fa3-8fbb-2b1c71b4be17">

**System info**
- inngest-cli version: 0.26.6-51ec78b6
- OS: [e.g. macOS]

**Additional context**

**Comment by homanp** [comment]
Hey @djfarrelly I updated to the latest `cli` version and start seeing this error.

**Comment by darwin67** [comment]
Hey folks, this issue should have been fixed.
