### ISSUE TITLE
Newest docker image causes _actual sync_ of invalid docker url to whatever env is pointed to by your env vars

### ISSUE THREAD

**Issue by kael-shipman** [inngest/inngest#1464]
**Describe the bug**

If your local `INNGEST_*` variables are set to real keys and you start your dev env against the local dockerized inngest mock server, it now syncs the (invalid) docker url to the env indicated in your env vars. This started happening as of the 0.29.1 release (for us, it was last Tuesday).

**To Reproduce**

1. Set `INNGEST_*` variables in your app to the real variables for dev environment
2. Instantiate docker container with the compose file below
3. Start app
4. Observe that the dev environment now has the url configured for the docker server.

_docker-compose.yml:_

```
services:
  inngest:
    image: inngest/inngest:latest
    command: inngest dev -u http://host.docker.internal:${PORT}/v1/inngest/webhook
```

(PORT is set to 3002 in our case, and `NODE_ENV` is set to either `local` or `development`)

**System info**
- inngest docker container version: 0.29.1
- OS: Mac, linux
- Version: latest macos, Xubuntu 22.04.4 LTS (kernel 6.5.0-28-generic)
- Docker: 26.1.3 (compose: v2.27.0)
- NodeJS: 20.12
- `inngest` client version: 2.6.0

**Screenshots**

These are the screenshots from our prod env. Note the url and also the every-5-seconds cadence. It seems to do this for a few minutes every 10 minutes or so.

![image](https://github.com/inngest/inngest/assets/3475586/95c9764d-2f50-4ea0-b3c4-1b932bb9af87)

**Comment by kael-shipman** [comment]
Bump. This just happened again :sob: . We're steps away from moving off of inngest because this has exposed how few controls there are (at least that we know about) to lock down an app configuration. At the end of the day, this is partly on us because someone has live credentials in their setup, but it also seems heinous that a dev setup would be able to change fundamental app configuration like this. If we could just lock the URL for the app, the bug would still exist but it wouldn't impact us anymore.

**Comment by goodoldneon** [comment]
@kael-shipman If I'm understanding the problem, our Dev Server is initiating production syncs when your app has production secrets. If that's correct, we introduced extra protection for this in version `3.6.2` of our SDK:
https://github.com/inngest/inngest-js/releases/tag/inngest%403.6.2. It's the "Forward `X-Inngest-Server-Kind` headers to assist in preventing some issues with registration handshakes" change.

The problem was that our SDK didn't tell Inngest Cloud if the Dev Server initiated the sync. After this change, we added information that Cloud can use to reject the sync. Unfortunately the fix is within the SDK so we're unable to add this protection to old SDK versions

**Comment by kael-shipman** [comment]
@goodoldneon that's fair and understandable. We've had "update inngest SDK" on our backlog for months, so maybe time to prioritize it. I think I've just been reticent because it's not clear if and how doing so will affect the behavior of our app, and of course inngest handles some mission-critical functions in our stack.... Anyway, we'll work on that.

In the meantime, it really would be nice for Inngest to simply prevent a client from updating it's own URL. The URL seems like a fundamental part of the app configuration that should be manually set through the UI, and it doesn't seem like something the app itself should be messing with.

Anyway, since it sounds like you know what's going on and the solution is simply to upgrade to the most recent version of the SDK, I'll go ahead and close this ticket. Thanks for the info!

**Comment by goodoldneon** [comment]
> it really would be nice for Inngest to simply prevent a client from updating it's own URL
This is a great idea -- we should add some sort of "URL lock" for apps! We can't do it for every app since it'll break for Vercel integration users (every Vercel deployment is a different URL), but for many users it makes total sense as an opt-in
