### ISSUE TITLE
init does not work on Windows

### ISSUE THREAD

**Issue by djfarrelly** [inngest/inngest#175]
**Describe the bug**
Running `inngest init` on Windows OS fails after selecting the language with the following error:

> There was an error creating the function: open .: invalid argument

**To Reproduce**
1. On Windows, install inngest cli
2. Run `inngest init` and select any options to scaffold a new functions
3. You should see the but

**Expected behavior**
I expect a new function to be created - the new files should all be created successfully in my new directory.

**Stack trace dump**
The error is thrown on this line in `template.go`: https://github.com/inngest/inngest/blob/e9071758252641f939eab2956eab59c3b410d0b0/pkg/scaffold/template.go#L156

It seems there are known issues with using `fs.WalkDir` as it uses `fs.FS`'s `Open()` function:

* https://github.com/golang/go/issues/44166
* https://github.com/golang/go/issues/44279

A potential solution ([see comment](https://github.com/golang/go/issues/44279#issuecomment-955778704)) is for us to not use `fs.FS` and `fs.WalkDir`, but instead re-implement this code (and any other similar `fs.Open`/`fs.WalkDir` usage) using `filepath.WalkDir`and `os.Open`. We also may have to use `filepath.ToSlash()` and/or make other modifications to the windows file paths to not throw issues. 

**System info**
- inngest-cli version: 0.5.0-rc2
- OS: Windows
- Version: 10

**Additional context**
I was not able to confirm if this caused any issues when running `inngest init` in [WSL](https://docs.microsoft.com/en-us/windows/wsl/)

**Comment by jpwilliams** [comment]
Works on WSL for me (with `v0.5.0-rc3`) 👍
