### ISSUE TITLE
Problem in timeout finish parsing

### ISSUE THREAD

**Issue by ragrag** [inngest/inngest#1967]
**Describe the bug**
Hello, 
i am getting the following errors when using ```timeouts``` on the inngest-dev server

```
6:16PM ERR devserver > Invalid request: json: cannot unmarshal string into Go struct field Timeouts.functions.timeouts.finish of type time.Duration
6:17PM WRN devserver > Invalid request:
json: cannot unmarshal string into Go struct field Timeouts.functions.timeouts.finish of type time.Duration
```

**To Reproduce**

Registering an inngest function with timeouts.finish e.g:

```ts
  inngest.createFunction(
      {
          id: `periodic-jobs/test.run`,
          name: `periodic-job/test.run`,
          retries: 3,
          timeouts: {
              finish: '600s',
          },
      },
      { event: `periodic-jobs/test.run` },
      async () => {},
  )
```

**Expected behavior**
Function registered properly 

**Screenshots / Stack trace dump**
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/a1b165b8-c146-46e4-93b2-da74a1d46425">

**System info**
- js inngest-sdk version: 3.25.1
- inngest-cli version: 1.1.0
- OS:  Sonoma 14.1

**Comment by djfarrelly** [comment]
Thanks - we're on it!

**Comment by djfarrelly** [comment]
Hi @ragrag - the fix will be out in the next release - we'll cut one on Monday!
