### ISSUE TITLE
redis-uri doesn't allow setting password "too many colons in address"

### ISSUE THREAD

**Issue by PatrickRogg** [inngest/inngest#2025]
**Describe the bug**
I'm selfhosting inngest and when I pass in the url to my redis server I receive the error **": too many colons in address"**

This is the formats I've tried: 

```
redis://:{REDIS_PW}@redis-master.redis.svc.cluster.local:6379
default:{REDIS_PW}@redis-master.redis.svc.cluster.local:6379
redis://default:{REDIS_PW}@redis-master.redis.svc.cluster.local:6379
```

**To Reproduce**
1. `inngest start --redis-uri redis://:{REDIS_PW}@redis-master.redis.svc.cluster.local:6379

**Expected behavior**
Being able to set the redis password in the `--redis-uri` flag

**Screenshots / Stack trace dump**
```
error creating redis client: dial tcp: address default:xxxx@redis-master.redis.svc.cluster.local:6379: too many colons in address
```

**System info**
- inngest-cli version: v1.3.1
- OS: Ubuntu
- Version 22

Thanks for your help.

**Comment by efernandes-dev-ops** [comment]
Currently experiencing the same issue +1

**Comment by djfarrelly** [comment]
`v1.3.3-beta.1` is out now with the changes in #2029 to hopefully fix this issue.

**Comment by djfarrelly** [comment]
Should be fixed in https://github.com/inngest/inngest/releases/tag/v1.3.3

Please let us know if it doesn't!
