### ISSUE TITLE
Allow unit testing individual functions

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest#224]
This feature request cropped up from a migration of Akka to Inngest.

**Aim**

As a developer, I want to make sure that my functions run as expected, with basic unit tests covering when a function is invoked and the steps that run.  Examples include:

- Being able to test that a function runs given a specific event
- Being able to test that a function _doesnt_ run given an event (eg. w/ expressions)
- Being able to test that steps run (using a mock driver, without actually running and compiling the steps)
- Being able to inject new events to test async flows

This is similar to our current E2E tests, but _better_:  instead of parsing logs the SDK and unit tests assert and wait for things to happen using a good API.

**Comment by doylio** [comment]
This was marked as completed, but I don't see anything in the docs about this.  Is this possible?
