### ISSUE TITLE
Does not find docker when using colima on mac.

### ISSUE THREAD

**Issue by gedw99** [inngest/inngest#260]
**Describe the bug**

Does not find docker when using colima on mac. 

``` 
func01 && /usr/local/bin/inngest run

Warning:  Looks like there was a problem loading Docker.                                                 
                                                                                                
 Docker is a required dependency for the CLI in order to build, run, and deploy your functions. 
                                                                                                
 You can find more information here: https://www.inngest.com/docs/installation/.                

 Error  unable to verify buildx platform support: exit status 1 
``` 

**To Reproduce**

0- install colima:

``` 
brew install colima
```

1. start colima

``` 
docker-start:
	# inngest needs docker ...
	colima start
	docker info
	# Get it colima and docker connected
	docker context use colima

	# List it
	docker context ls

	# Test it
	docker info
	docker ps
``` 

2. make a func

``` 
inngest init ..... 
``` 

3. run it

``` 
inngest run 
``` 

**Expected behavior**

Should find Docker.

**Screenshots / Stack trace dump**
If applicable, add screenshots or paste what is output in your terminal to help explain your problem.

**System info**
- inngest-cli version: [e.g. 1.0.2]
- OS: [e.g. macOS]

**Additional context**

**Comment by gedw99** [comment]
I suspect that the docker context is not being respected.

**Comment by jpwilliams** [comment]
Thanks for the detailed report!

It may be that `colima` doesn't include the `buildx` plugin by default.

Could you try the [instructions on the docs](https://www.inngest.com/docs/cli/installation) to manually install it? abiosoft/colima#273 seems to follow the same process.

I'll try to reproduce this to confirm too. If `buildx` is the issue, at the very least we can push a better error message that highlights that requirement.
