### ISSUE TITLE
`inngest types ts` generates different ordering of types every time it is run

### ISSUE THREAD

**Issue by umar-ahmed** [inngest/inngest#316]
**Describe the bug**

When running `inngest types ts` at different times without changing the event schemas on Inngest Cloud, the ordering of the event keys in the generated code changes randomly. This produces unnecessary diffs when working on unrelated code changes.

**To Reproduce**

1. Create a Next.js project using Yarn
2. Add `inngest` and `inngest-cli` as dependencies
3. Add a `predev` script to package.json as described in [this doc](https://www.inngest.com/docs/typescript)
4. Run `yarn dev`
5. Commit the changes
6. Run `yarn dev` again
7. See that the ordering of the event keys changes producing a diff

**Expected behavior**

I would expect that the code generation would be deterministic with respect to the ordering given no additions or deletions. Ideally it is ordered alphabetically, so as to respect the event prefixes.

**Screenshots / Stack trace dump**

<img width="864" alt="CleanShot 2022-12-16 at 11 27 05@2x" src="https://user-images.githubusercontent.com/8302959/208144120-5386e12d-5052-4d23-8673-10a01fbe2bd9.png">

<img width="1198" alt="CleanShot 2022-12-16 at 11 05 53@2x" src="https://user-images.githubusercontent.com/8302959/208141732-2ef110b8-1b41-4335-a829-098d68056cd9.png">

**System info**
- inngest-cli version: 0.8.3
- OS: macOS
- Version 13.0.1 (Ventura)

**Additional context**

I also tried not installing the `inngest-cli` as a project dependency, and using `npx` directly and I had the same behaviour.

**Comment by tonyhb** [comment]
Oh damn yeah, thanks for reporting.  This is due to go's implementation of randomly shuffling maps to prevent bugs, as they don't guarantee order so they force it on you.

We'll do some work our side to make this deterministic so that git diff doesn't show anything like this.

Also, thoughts on hiding built-in events? 🤔

**Comment by umar-ahmed** [comment]
> Oh damn yeah, thanks for reporting.  This is due to go's implementation of randomly shuffling maps to prevent bugs, as they don't guarantee order so they force it on you.
> 
> We'll do some work our side to make this deterministic so that git diff doesn't show anything like this.

Awesome, thank you!

> Also, thoughts on hiding built-in events? 🤔 

I honestly don't even know what those are for. If they could be removed if I'm not using them, then that would be ideal.
