### ISSUE TITLE
Live refresh of function runs, events etc.

### ISSUE THREAD

**Issue by flobaader** [inngest/inngest#320]
**Is your feature request related to a problem? Please describe.**
In my observation the UI needs manual refresh when new results appear, e.g. when viewing a function run.

**Describe the solution you'd like**
Provide a live status of the UI, where no manual refresh is needed, when new events occur or functions are updated.

**Comment by djfarrelly** [comment]
Hi @flobaader, this is a great idea. Are you suggesting to add this to the local development server UI (`dev` command) or the Inngest Cloud dashboard?

We believe the dev server should update automatically, but we're aware that we don't push updates in our cloud UI. Similar to what you suggested in #321, we moved over to an entire new queueing and state system as of last week (starting w/ #305) and one of the features will be to offer improved, realtime job status. As we re-design the cloud UI, we're planning to add more realtime feedback and status to the interface.

We appreciate the feedback and we are definitely hoping to add this to our app in the near future!

**Comment by tonyhb** [comment]
Handled within the new UI.  Thank you!
