### ISSUE TITLE
Function call times vary too much and are too high

### ISSUE THREAD

**Issue by flobaader** [inngest/inngest#321]
**Describe the bug**
I have observed the some function calls take a very long time (> 3 minutes). In general they vary in my setup between 1 and 5 seconds.

This function run for example has not shown any new events since 10 minutes

<img width="886" alt="image" src="https://user-images.githubusercontent.com/16624361/208370630-55498cf6-a76a-409f-880b-8c5a047fca41.png">

In general I think the time is still very long, e.g. if I want to load some data after user registration and the user has to wait multiple seconds or minutes.

Is this just a scaling issue of your current prod deployment or caused by the architecture?

**Expected behavior**
I would expect a function call in 100 ms or at least < 1sec.

**Comment by flobaader** [comment]
Ah what I forgot: Of course it could be that the function is still running, maybe another log message for that would be awesome to see whats going on.
(e.g. the function is still running after a few seconds)

**Comment by flobaader** [comment]
But since I can not see a HTTP call for the function in my deployment, I don't think that the function is really running ATM

**Comment by djfarrelly** [comment]
Hi @flobaader, thanks for reporting this. This is a known issue in our production system that we are actively working right now. We agree that this isn't acceptable and will be reducing this greatly to being as fast as possible in the coming days!

---

> Is this just a scaling issue of your current prod deployment or caused by the architecture?

This is a scaling issue of our production deployment.

For some context, with increased usage over the last few weeks, we have identified a bottleneck in the part of our production system that externally calls functions via HTTP. This system utilizes [Nomad](https://www.nomadproject.io/) to run containers which execute these jobs and our system has hit the limitations of Nomad for this use case. We hit this limit earlier than anticipated, so we are moving over to a planned new solution as soon as possible. Our team was working on this over the weekend to replace Nomad completely. The new solutions should drastically improve performance and increase our ability to scale by orders of magnitude. 

We will update here when this new system is out in production for Inngest Cloud!

**Comment by tonyhb** [comment]
Hey @flobaader, appreciate the response here.  We've moved over to a new internal RPC-based system for executing SDK-based functions via HTTP;  the latency should be much lower.  In our tests in in the order of milliseconds for each call.

This should now be fixed.
