### ISSUE TITLE
Support wildcard event triggers e.g. `something/*`

### ISSUE THREAD

**Issue by djfarrelly** [inngest/inngest#326]
**Describe the bug**
In Inngest Cloud, wildcard event triggers are supported, but they are not well supported in the SDK or CLI.

**To Reproduce**
1. Create a function w/ the event trigger `test/*`
2. Send an event to the dev server `test/whatever` and `test/another`
3. No function gets run

**Expected behavior**
I expect the functions to run. 

I had to create a combination event type for the SDK to work correctly. Example:

```js
export const inngest = new Inngest<
  Events<{
    "test/*": Test__Whatever | Test__Another;
  }>
>({
  name: "App",
});
```

**Screenshots / Stack trace dump**
n/a

**System info**
- inngest-cli version: 0.8.4

**Additional context**
n/a

**Comment by jpwilliams** [comment]
This is cool.

Can the wildcards be anywhere, e.g. `test/so*thing`? Or is it limited to `scope/*`?

We could look at template types, perhaps, though I think that's usually based on calculating all permutations of the given variables, so it might struggle here if the wildcards can be anywhere.

At the very least we could look at providing `scope/*` helpers which just roll up potential types within that scope as you've done here.

Or even helpers for `app/user.*`; for every separator, be it `/` or `.`.

🤔

**Comment by djfarrelly** [comment]
I believe the wildcard is only valid at the end of a trigger to work as expected. (Since event triggers are strings, really anything can be accepted by the API). I think the key thing would be to ensure this works in the dev server repo and then we can document how to do it with the SDK manually or otherwise.

**Comment by tonyhb** [comment]
Handled, though types are necessary.  cc @jpwilliams on the SDK
