### ISSUE TITLE
Event source webhook emulator does not allow you to enter an incoming event

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest#357]
I assume (but I could be wrong) that the point of this emulator was to allow you to see how the transform function would work on and incoming event.

1. Create a source of type webhook
2. Enter a transform function
3. Attempt to type in the incoming event box

The cursor moves to the transform when you type. (Safari on a Mac)

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/375005/212890693-bf1ad127-ec9a-41c8-bfbb-732e28e067e6.png">

**Comment by tonyhb** [comment]
Fix by @djfarrelly earlier today.  Thanks for reporting1
