### ISSUE TITLE
Make function failures more obvious

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest#358]
I invoked 5 functions, 4 successfully and 1 failed (to test failures).

I expected to see a big red flashing light and email notifications saying a function failed.

But a see a green dot on the failed function and no errors shown in the overview, If I had not intentionally failed that function I would not have known it had failed. 

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/375005/212954599-a85fc425-8b80-461b-9046-8e78b26580cd.png">

You only see there is something wrong when you go into the details.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/375005/212956387-18c20896-c888-4d39-87db-3be27c173e0e.png">

**Comment by tonyhb** [comment]
100% - this is a great point and I'll jump on this one for you.  Assigning to me and will let you know when it's done — within the next day.

We're working on a _broad_ redesign of this entire UI, including alerting, monitoring, etc.  It'll make this look way nicer.

**Comment by DaleLJefferson** [comment]
Thanks @tonyhb I really appreciate you looking at this as a matter of urgency. ⭐

**Comment by tonyhb** [comment]
This is now live within Inngest.  We're revisiting this UI in entirety very, very soon as well — lots more improvements coming for observability.
