### ISSUE TITLE
List function failures (Errors Tab)

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest#359]
Thanks for sorting out #358 I can see there are failures but my only way to see the errors is to page through thousands of errors.

Ideally I would have two tabs "All Runs" & "Errored Runs" so I can easily see all the failing function runs.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/375005/213143856-6bb394aa-4902-457c-9b2e-5dcba00510ec.png">

**Comment by tonyhb** [comment]
Taking this one — we're entirely redesigning this right now but I'll push out some changes to the current design today.

**Comment by tonyhb** [comment]
This has been pushed live — won't delay the new designs but can say that it will look SO much better soon!!
