### ISSUE TITLE
Event Latency Charts

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest#366]
I'm using inngest with a realtime WhatsApp chatbot so latency is pretty important (A person is waiting for the response)

Latency = Time from when the event was received to the time the function was invoked.

I believe there is a default function concurrency and potentially custom ones in the future. If concurrency is set to 100 and I put 10,000 events into the queue it would be good to see the latency and adjust concurrency.

**Comment by DaleLJefferson** [comment]
At the moment my event -> function ratio is one to one, I had not thought about having different functions (potentially with different rates)

So I guess event and function queue stats.

1. Event / Function latency over time graph.
2. Event / Function number of items in the queue vs concurrency limit over time graph.
3. I had not thought about "Time for backlog to be exhausted" sounds great, if I put 10,000 events into the queue it would be great to know how long it will take to clear.
4. Function run time would be great as well, you know when you invoked a function and when it returned

To be honest I will have a better idea once I throw 10,000 events into the system, at the moment I did 400 events and had to keep refreshing the function page to see stuff happening, which was underwhelming.

A large part of the appeal of inngest is the promise of visualising these jobs (Previously we had SQS and cloudwatch). The dream would be a fancy attractive real time chart with all the information at a glance.

**Comment by tonyhb** [comment]
Handled within the cloud, via real-time time series metrics.  Thanks for the thoughts here, @DaleLJefferson!
