### ISSUE TITLE
Delay event

### ISSUE THREAD

**Issue by DaleLJefferson** [inngest/inngest#368]
I would be really nice if the event creator could specify directly the event delay time.

> Simple things should be simple, complex things should be possible!

```js
{
    name: "send_email",
    data: {},
    delay: "5m"
}
```

```js
{
    name: "send_email",
    data: {},
    notBefore: "2023-04-01T12:30:00"
}
```

With the current system my understanding would be I would have to do this.

```js
{
    name: "send_email",
    data: {
        delay: "5m"
    }
}

export const fn = inngest.createStepFunction(
  "Send email",
  "send_email",
  ({ event, tools }) => {
    tools.sleep(event.data.delay);
    tools.run("Do some work in the future", async () => {
      // Do work
    });
  }
);
```

The step system looks really powerful but I would suggest overkill for this simple use case.

The same pattern could be use for events that wait for other events (Again another powerful system)

```js
{
    name: "send_reminder_email",
    data: {},
    waitForEvent: {
        name: "app/post.created",
        match: "data.user.id",
        timeout: "24h"
    }
}
```

**Comment by tonyhb** [comment]
Handled — future `ts` delay functions.  Thank you!
