### ISSUE TITLE
Function error callbacks

### ISSUE THREAD

**Issue by tonyhb** [inngest/inngest#370]
This issue outlines the ability to create functions called automatically any time functions permanently fail.  Failure functions can be their own step functions and should be called with the latest error and the incoming event.  This allows users to run any logic necessary for eg. cleanup, alerting, logging, etc.

**Why**

Even though functions and steps automatically retry, sometimes failures happen.  We need to be able to handle these failures individually as they happen.

**Some specific use cases:**

- As a developer, I want to run a cleanup function any time my functions fail permanently
- As a developer, I want to update the status of a row in my DB if my functions fail permanently

**Current nomenclature**

- A step or function can “error” and will retry.  If all attempts error the step and function is a “failure”.
- A “failure” is permanent.

**Questions**

- Is it possible to add more than one error/fail handler to a function within the SDK?
- What data should we send to the error handler? (This is outlined in detail below)
    - Specifically, should we send the serialized function state within the event?  What if this is ≥= the event limit size?
- Given failures are permanent, should the SDK use `onFailure` vs `onError`?

### Product Spec

**High level**

We can leverage the existing architecture to easily build error handlers.  At a high level:

- Add an `onError` (or `onFailure` - see nomenclature above) option to `createFunction` in our SDK.
    - These failure functions automatically get a trigger of `inngest/function.failed` with an expression matching the current function ID
    - The SDK deploys the failure functions alongside the regular functions when communicating with Inngest
- When a function’s status updates to `Failed`, send an `inngest/function.failed` event to the current workspace.
    - The event’s data contains the function ID and error, automatically triggering the error handler

**`inngest/function.failed` structure**

```tsx
type FailureEvent<T> = {
  name: "inngest/function.failed",
  data: {
    function_id: string;
    run_id: string;
    error: {
      message: string;
      stack?: string;
      cause?: string;
      status?: number
    },
    event: T // The event which triggered the original function
  }
}
```

**SDK API**

```tsx
createFunction(
  {
    name: "Signup flow",
    // onFailure sticks to our error vs fail nomenclature, but is less standard than onError.
    // This could also be `onError`.
    onFailure: ({ event, tools }) => {
      // Event is of type FailureEvent<AuthUserCreated>
    }, 
  },
  "auth/user.created",
  ({ event, tools }) => {
    // ...
  }
);
```

The SDK should automatically add the error handler’s function config with a conditional trigger:

```tsx
triggers: [{
  event: "inngest/function.failed",
  expression: `event.data.function_id == "${GENERATED_FUNCTION_ID}"`
}]
```

Where `GENERATED_FUNCTION_ID` is the original function’s ID generated by the SDK.

**Rollout**

- Update the dev server and cloud to trigger `inngest/function.failed` events with the above type.
- Update the SDK’s `createFunction` options, allowing error functions to be defined.
    - Ensure that the SDK automatically sends configuration for error handlers with the correct triggers:

**Documentation**

- Update the SDK reference
- Add error handling to the “Writing functions” docs
- Add a new guide

**Comment by danthegoodman1** [comment]
```
onFailure: ({ event, tools }) => {
      // Event is of type FailureEvent<AuthUserCreated>
    }, 
```

I like this, but if we could include why it failed (nonretryable, timeout, internal) that would be ideal as well

**Comment by danthegoodman1** [comment]
Or maybe I am blind and did not read properly, but I think `event` should still be the same as the initial event that triggered it.

**Comment by umar-ahmed** [comment]
Thoughts on moving `onFailure` to top-level param instead?

```js
createFunction(
  "Signup flow",
  "auth/user.created",
  ({ event, tools }) => {
    // ...
  },
  ({ event, tools }) => {
    // Event is of type FailureEvent<AuthUserCreated>
  }
);
```

This would make it similar to `Promise.then(onFulfilled, onRejected)` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)

**Comment by danthegoodman1** [comment]
Not a fan personally

**Comment by jpwilliams** [comment]
> [...] if we could include why it failed (nonretryable, timeout, internal) that would be ideal as well
> 
> [...] I think `event` should still be the same as the initial event that triggered it. Otherwise feels a bit confusing.

@danthegoodman1 Yeah, agreed. Perhaps `{ event, cause }` would be reasonable.

---

> Thoughts on moving `onFailure` to top-level param instead?
> This would make it similar to `Promise.then(onFulfilled, onRejected)`

@umar-ahmed Yes! I thought perhaps we'd have to do this anyway to get inference working nicely, but it seems it'd be fine without as the event trigger is still a separate parameter.

In two minds about this - it feels good that this pattern matches some JS signatures quite closely, but I'd wager lots of folks aren't aware of the `onRejected` parameter that can be passed to `.then()`; a benefit of having an `onFailure` key within the options block feels like increased discoverability, at the cost of potentially bundling in a large function in the middle of a load of options. 🤔

**Comment by umar-ahmed** [comment]
> In two minds about this - it feels good that this pattern matches some JS signatures quite closely, but I'd wager lots of folks aren't aware of the `onRejected` parameter that can be passed to `.then()`; a benefit of having an `onFailure` key within the options block feels like increased discoverability, at the cost of potentially bundling in a large function in the middle of a load of options. 🤔

@jpwilliams That reasoning makes sense to me. I wanted to suggest it though because it feels a bit strange reading code where the error handler comes before the body of the handler. But I don't really mind, I can always just extract it as a variable and move it wherever I want

**Comment by jpwilliams** [comment]
> @khill-fbmc: I think I might have realized I can try/catch that step and reason with the failure that way....

Yeah, that's the intended path, but we don't handle errors per-step just yet. So, while my answer for this would ideally be to use `try`/`catch` or `.catch()`, that won't quite work as expected until we add that capability to the executor.

The best approach at present would be to bundle the error with the step result. We could write a helper function for this:

```ts
/**
 * Wraps the given function to ensuring it always resolves, providing access to
 * the error if it would have otherwise rejected.
 */
const wrapResult = <T extends () => unknown>(
  fn: T
): (() => Promise<
  { ok: true; value: ReturnType<Awaited<T>> } | { ok: false; error: any }
>) => {
  return async () => {
    try {
      return { ok: true, value: (await fn()) as ReturnType<Awaited<T>> };
    } catch (err) {
      return { ok: false, error: err };
    }
  };
};
```
Then use it like so:
```ts
inngest.createFunction(
  { name: "Hello World" },
  { event: "demo/hello.world" },
  async ({ step }) => {
    const thing = await step.run(
      "label",
      wrapResult(async () => {
        // your usual step.run function code
      })
    );

    if (thing.ok) {
      // happy path
      // access thing.data
    } else {
      // failed
      // access thing.error
    }
  }
);
```
It's pretty unideal, but that workaround should give you some per-step error handling before we add it natively.
