### ISSUE TITLE
docs: step.sendEvent() is not documented in the 'Step Tools' section

### ISSUE THREAD

**Issue by grempe** [inngest/inngest#400]
In the `Step Tools` section of the docs, where functions available to `step` are documented, the `sendEvent()` function is not documented:

https://www.inngest.com/docs/functions/multi-step#step-tools

This seems especially important to document per this instruction found elsewhere:

```txt
Why step.sendEvent vs inngest.send?

By using step.sendEvent Inngest’s SDK can automatically add context and tracing which ties events to the current function run. If you use inngest.send the context around the function run is not present.
```

The only place I have found this documented, unless I missed it, is:

https://www.inngest.com/docs/guides/fan-out-jobs#why-step-send-event-vs-inngest-send

This seems to be information that should be highlighted.

**Comment by jpwilliams** [comment]
Looks like this is documented in our reference now: https://www.inngest.com/docs/reference/functions/step-send-event
