### ISSUE TITLE
Event Dropdown in Panel

### ISSUE THREAD

**Issue by khill-fbmc** [inngest/inngest#411]
**Is your feature request related to a problem? Please describe.**
I find it tedious to have to type out event names, or copy paste them into the event sender.

**Describe the solution you'd like**
It would be nice to have a pre-populated dropdown with the events. They are already loaded into the page as you can see in the list below the textarea.

![image](https://user-images.githubusercontent.com/107003416/225305344-d60fca2c-f544-4ed9-a11f-ff2757a13c9d.png)

**Comment by tonyhb** [comment]
Handled with the dev server.  Thanks @khill-fbmc!
