### ISSUE TITLE
Gripe: Having to redeclare the event name twice is annoying

### ISSUE THREAD

**Issue by sinclairnick** [inngest/inngest#425]
**Is your feature request related to a problem? Please describe.**
Currently, one must declare the name of an event twice, in the payload def and in the `Events` object. This is both a bit annoying and duplicated work, but also leaves room for error, considering the payload `name` key and the object key aren't validated against each other.

**Describe the solution you'd like**
Do smarter TS inference where the name is inferred automatically, by either object key or `name` property.

This can trivially be achieved by using a wrapper type like

```ts
type _InngestEvents = {
  "some-event": {
    // `name` will be inferred as `some-event` 
    data: { foo: "bar" }
  }
}

export type InngestEvents = {
  [K in keyof _InngestEvents]: _InngestEvents[K] & {
    name: K;
  };
};
```

Apologies for the nitpicking, but its also pretty trivial to fix, and I think little improvements like this could improve adoption!

**Comment by djfarrelly** [comment]
We're working on an more intuitive and extensible solution in this PR: https://github.com/inngest/inngest-js/pull/66

**Comment by jpwilliams** [comment]
Hi, @sinclairnick!

Closing this as the changes mentioned above have moved into v2 of the TS SDK. Check out [Defining Event Payload Types](https://www.inngest.com/docs/reference/client/create#defining-event-payload-types) section on our docs to see what this looks like now. 🙂
