### ISSUE TITLE
Include more metadata in the async driver response

### ISSUE THREAD

**Issue by goodoldneon** [inngest/inngest#439]
**Is your feature request related to a problem? Please describe.**
For the step metric project we'd like to include the following information about each completed step:
- Attempt count
- Duration
- Output size
- Generator stack index

The stack index will be used to differentiate the first "generator" step (e.g. `step.run()`) from the other generator steps. Additionally, we want to differentiate the first generator step from the implicit function step.

**Describe the solution you'd like**
The async driver includes the necessary metadata in its response.

**Comment by tonyhb** [comment]
Closing — this is handled.
