### ISSUE TITLE
[BUG] concurrency not working for me

### ISSUE THREAD

**Issue by the-research** [inngest/inngest#446]
**Describe the bug**
I set { concurrency: 1 } and it's run all of the functions (in local inngest-server, "npx inngest-cli@latest")

**To Reproduce**
1. Create a function that call to "step.sendEvent" with array of 10 items (to another function)
2. Set { concurrency: 1 } to the other function and put "step.sleep('5s')"

**Expected behavior**
Expected to the functions to finish at 10 (items) * 5 seconds => 50 seconds. However everything finished in 5 seconds.

**System info (please complete the following information):**
- OS: Mac
- node version: 18.6.0
- npm package Version: 9.5.1
- Framework: Next.js
- Platform: Local machine

**Comment by tonyhb** [comment]
Fixed in the latest version of the dev server!
