### ISSUE TITLE
Run Python functions

### ISSUE THREAD

**Issue by homanp** [inngest/inngest#476]
**Describe the solution you'd like**
Possibility to run `Python` functions as an alternative to `Typescript`.

If this is something that fits the scope I would be happy to contribute.

**Comment by homanp** [comment]
Found this: https://github.com/inngest/inngest-python is this something that is runnable?

**Comment by tonyhb** [comment]
Not for functions... yet.  We've got a beta Go SDK and one coming for Elixir — this is something that needs to be added!  We also have a spec for writing SDKs.  Definitely open to help get this in;  the SDKs are stateless and push-based, so it's not too complex to add!

**Comment by jpwilliams** [comment]
@goodoldneon has been working on the Python SDK, @homanp! 🥳
Check out [Python SDK - Inngest Documentation](https://www.inngest.com/docs/reference/python).

I'll close this as we have something in the works and can continue any discussion in that repo.

**Comment by homanp** [comment]
> @goodoldneon has been working on the Python SDK, @homanp! 🥳
> 
> Check out [Python SDK - Inngest Documentation](https://www.inngest.com/docs/reference/python).
> 
> 
> 
> I'll close this as we have something in the works and can continue any discussion in that repo.

Yes!
