### ISSUE TITLE
--no-discovery causes inngest server to not register app at the url provided using -u

### ISSUE THREAD

**Issue by shivghai** [inngest/inngest#505]
**Describe the bug**

`--no-discovery` causes inngest server to not register the inngest sdk url provided using `-u`. 

Running `npx inngest-cli@latest dev --no-discovery -u http://localhost:8910/api/inngest` doesn't attempt any registrations **at all**. Manually going to the inngest server url and registering the endpoint/app using the UI works.

Running without the `--no-discovery` flag, the app is registered successfully, but there is a lot of noise with attempted registrations for `.netlify`, `.redwood` etc.

**To Reproduce**
1. Run app server (for us, `yarn rw dev`)
2. Run `npx inngest-cli@latest dev --no-discovery -u http://localhost:8910/api/inngest`

**Expected behavior**
Expect the app server to get hit when providing the url via `-u` and disabling *autodiscovery*. Let me know if that's not the expected behavior

**Screenshots / Stack trace dump**
If applicable, add screenshots or paste what is output in your terminal to help explain your problem.

**System info**
- inngest-cli version: 0.15.1
- OS: macOS

**Comment by tonyhb** [comment]
Fixed in 0.14.2 - thank you!
