### ISSUE TITLE
Running server from latest docker image doesn't working

### ISSUE THREAD

**Issue by octoper** [inngest/inngest#526]
**Describe the bug**
I have been trying to run the Inngest server with the latest Docker image but the command to run the command that is mention in the [Self Hosting](https://www.inngest.com/docs/self-hosting) doc doesn't working.
This was not the case before these changes https://github.com/inngest/inngest/commit/55d86b72239addd86735adf00b8a374e9445b4d8

**To Reproduce**
1. Run `docker run -d --restart always --name runner inngest/inngest:latest inngest serve runner`

**Expected behavior**
Start the Inngest server.

**Screenshots / Stack trace dump**
```
docker: Error response from daemon: Conflict. The container name "/runner" is already in use by container "1478a42245d3eaed7759f0f271f3350a140714af0f117e8106f2667bca2a32e2". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**System info**
- OS: macOS
- Version: 13.4.1

**Comment by tonyhb** [comment]
Fixed!

**Comment by octoper** [comment]
Thank you!
