### ISSUE TITLE
Local server not running when entering command

### ISSUE THREAD

**Issue by pullmann4rent** [inngest/inngest#562]
Hello,

I want to start the local server and entered "npx inngest-cli@latest dev" in my cmd then I got the message do you want proceed (y) I typed " y " then installed and then nothing happens. The local server not starting. What can be the problem there why I cant start the local server ?

![cmd](https://github.com/inngest/inngest/assets/123197323/4edd65ac-bf6a-4e2b-aaec-3fc877861e87)

**Comment by charanjit-singh** [comment]
Same issue

**Comment by charanjit-singh** [comment]
Seems like there's some issue with the latest version, let me try to use lower version

**Comment by charanjit-singh** [comment]
For now I'm able to run it in docker using following commands:

```
docker build -f ./docker/ingest.Dockerfile -q .
docker run --publish 8288:8288 "Output of above"
```

Here's my dockerfile
```
FROM node:latest

RUN npm install -g inngest-cli@latest

CMD ["npx", "inngest-cli", "dev"]

# Expose port 8288
EXPOSE 8288

```

**Comment by charanjit-singh** [comment]
![image](https://github.com/inngest/inngest/assets/23359602/1ba5d70d-e436-431f-a065-a841d0614d42)

Didn't work

**Comment by charanjit-singh** [comment]
Updated Dockerfile

```
FROM node:latest

RUN npm install -g inngest-cli@latest
RUN npm install -g http-server
RUN npm install -g concurrently


CMD ["concurrently","inngest-cli dev -u http://localhost:3000/api/inngest", "http-server -p 3000 -P http://host.docker.internal:3000"]

# Expose port 8288
EXPOSE 8288

```

**Comment by jpwilliams** [comment]
Hi, @pullmann4rent and @charanjit-singh! 👋 Thanks for reporting.

I'm hoping this issue is now be resolved in [v0.16.4](https://github.com/inngest/inngest/releases/tag/v0.16.4) following #575.

Could you try again for me with `npx inngest-cli@latest dev`?

**Comment by achan-godaddy** [comment]
not sure if this is related @jpwilliams but running on an m1 mac (ventura 13.5) seems to end silently without any message.  I'm using volta to manage node and have tried node 16, 18, and 20 latest and all have the same result.  Have also tried `npx inngest-cli@latest`, `npm i -g inngest-cli`.  I'll try the docker route for now but might be useful to have an official docker for local dev.

**Comment by jpwilliams** [comment]
Hi, @achan-godaddy! 👋

Could you run a couple of commands for me and share the output? npm is a bit mean and hides errors in postinstall scripts by default.

Note that both commands will output some local paths you can redact if you wish.

```sh
# Shows OS, Node versions
npx envinfo@latest --system --binaries
```

```sh
# Shows output from our postinstall script
DEBUG=inngest:* npm i -g --foreground-scripts inngest-cli@latest
```

**Comment by achan-godaddy** [comment]
@jpwilliams thanks, that led me to the answer.  So the output of the debug was entirely empty, which made me remember that I disable postinstall scripts by default.

I typically leave scripts off `ignore-scripts=false` in my `~/.npmrc`. I was expecting that the bin from the cli would be downloading the binary and not a postinstall script but didn't get any error message from the `inngest-cli`.  Re-enabling scripts, uninstalling and re-installing resolved it. 👍

**Comment by jpwilliams** [comment]
@achan-godaddy Aha - got it.

We can add this to a debugging section somewhere for if folks get this in the future; thank you for the update!

Will close this as solved.
