### ISSUE TITLE
Dev server not showing failed step name

### ISSUE THREAD

**Issue by Thinkscape** [inngest/inngest#774]
## Description

Whenever a step fails (throws) the dev server shows `...` instead of step id.

## To Reproduce

```ts
inngest.createFunction({ id: 'foo' }, {event:'on-foo'},
async ({ step }) => {
   await step.run('this-might-fail', () => {
    throw new Error('oops');
   });
});
```

## Expected behavior

Dev server clearly shows step `this-might-fail` has failed.

## Actual

<img width="637" alt="image" src="https://github.com/inngest/inngest/assets/270528/a857e9c1-08d1-4260-8866-642411be82fc">

## System info
- `inngest/inngest:latest` image `7a013c9b5817`
- OS: macOS sonoma
- Inngest js `3.1.1`

**Comment by imagine-erik** [comment]
I'm experiencing this same thing on both the dev server and production.

**Comment by Thinkscape** [comment]
May we have some 👁️👁️ on it please?

The dev UI could use some love to bring it up to speed with latest features and breaking changes ...

**Comment by jainpawan21** [comment]
> May we have some 👁️👁️ on it please?
> 
> The dev UI could use some love to bring it up to speed with latest features and breaking changes ...

@Thinkscape I see, in dev server, failed step id is shown before this 3 dot item.
