### ISSUE TITLE
Add App in dev mode not working

### ISSUE THREAD

**Issue by ali-master** [inngest/inngest#930]
**Describe the bug**
I'm running a simple project based on documentation, but I got this error:
```txt
sql: Scan error on column index 5, name \"created_at\": unsupported Scan, storing driver.Value type string into type *time.Time
```

**Expected behavior**

**Screenshots / Stack trace dump**
If applicable, add screenshots or paste what is output in your terminal to help explain your problem.

**System info**
- inngest-cli version: 0.23.0
- OS: macOS
- Inngest Version: 3.7.0

**Additional context**
`http://127.0.0.1:8288/v0/gql` Response:
```json
{
    "errors": [
        {
            "message": "sql: Scan error on column index 5, name \"created_at\": unsupported Scan, storing driver.Value type string into type *time.Time",
            "path": [
                "apps",
                0,
                "functions"
            ]
        },
        {
            "message": "sql: Scan error on column index 5, name \"created_at\": unsupported Scan, storing driver.Value type string into type *time.Time",
            "path": [
                "apps",
                0,
                "functionCount"
            ]
        }
    ],
    "data": null
}
```

**Comment by ali-master** [comment]
Any news?

**Comment by octalpixel** [comment]
Hey @ali-master Did you happen to get a solution to this ?

**Comment by tonyhb** [comment]
@octalpixel @ali-master we're deep diving this one now after many unsuccessful repro attempts.  a fix will be here shortly.

**Comment by tonyhb** [comment]
@octalpixel @ali-master v0.24.2 is out with @goodoldneon's fix.  Thanks for reporting!
